title: "First Principles"
subtitle: "A knowledge base built from the ground up"
name: "Quinn Cohen"
description: "Exploring epistemology, behavioral economics, and foundational math."
url: "https://qtanarose.github.io"
baseurl: "/philosofein"
author:
  name: "Quinn Cohen"
  bio: "Curious about the why behind everything."
  location: "CA"
  avatar: "/assets/images/bio-donut.jpg"

minimal_mistakes_skin: "aqua"
