title: "First Principles"
subtitle: "A knowledge base built from the ground up"
name: "Quinn Cohen"
description: "Exploring epistemology, behavioral economics, and foundational math."
url: "https://qtanarose.github.io"
baseurl: "/philosofein"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

paginate: 5
paginate_path: /page:num/

minimal_mistakes_skin: "sunrise"

include:
  - _pages

author:
  name: "Quinn Cohen"
  bio: "Curious about the why behind everything."
  location: "CA"
  avatar: "https://qtanarose.github.io/philosofein/assets/images/bio-donut.jpg"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true

      include:
  - _pages

collections:
  categories:
    output: true
